menu:
    Blog: /
    Archive: /archives/
    Essay: /categories/essay
    Technology: /categories/technology/
    Literature: /categories/literature/
    GitHub: https://github.com/weilinonline
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2015
